# Generated by Django 5.1.4 on 2024-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usable_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='usable password'),
        ),
    ]
